#!/usr/bin/env node
/**
 * Turns the reviewable TSVs into the JSON that bootstrap loads.
 *
 *   node seed/build-seed.mjs
 *
 * Writes seed/ingredients.json, seed/substitutions.json and seed/REVIEW.md.
 * Nothing is hand-edited in the JSON — edit the TSV and rebuild.
 *
 * REVIEW.md is generated from the `confidence` column rather than curated by
 * hand, so the review list is complete by construction. A list of "things I
 * happened to remember being unsure about" would quietly omit the entries
 * whose wrongness was not obvious, which are the dangerous ones.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

const chr10 = String.fromCharCode(10);

const splitList = (s) =>
  s
    .split(',')
    .map((x) => x.trim())
    .filter(Boolean);

function readTsv(file, columns) {
  const rows = [];
  const lines = readFileSync(join(HERE, file), 'utf8').split('\n');
  lines.forEach((raw, i) => {
    const line = raw.replace(/\r$/, '');
    if (!line.trim() || line.startsWith('#')) return;
    const parts = line.split('|');
    if (parts.length !== columns.length) {
      throw new Error(
        `${file}:${i + 1} has ${parts.length} fields, expected ${columns.length}\n  ${line}`,
      );
    }
    rows.push({ __line: i + 1, ...Object.fromEntries(columns.map((c, j) => [c, parts[j].trim()])) });
  });
  return rows;
}

/* ------------------------------- ingredients ------------------------------ */

const ingredientRows = readTsv('ingredients.tsv', [
  'canonical_id',
  'name',
  'aliases',
  'category',
  'default_unit',
  'default_shelf_days',
  'allergens',
  'diet_flags',
  'confidence',
  'review_note',
]);

const ingredients = ingredientRows.map((r) => ({
  canonical_id: r.canonical_id,
  name: r.name,
  // An alias identical to the canonical_id is redundant: the resolver already
  // indexes the id. Stripping it here keeps the TSV forgiving to write.
  aliases: splitList(r.aliases).filter((a) => a.toLowerCase() !== r.canonical_id.toLowerCase()),
  category: r.category,
  default_unit: r.default_unit,
  default_shelf_days: r.default_shelf_days === '' ? null : Number(r.default_shelf_days),
  allergens: splitList(r.allergens),
  diet_flags: splitList(r.diet_flags),
  // Seed metadata. bootstrap.ts drops these before the D1 insert; the
  // `ingredients` table has no such columns.
  confidence: r.confidence,
  review_note: r.review_note,
}));

/* ------------------------------ substitutions ----------------------------- */

const substitutionRows = readTsv('substitutions.tsv', [
  'from_id',
  'to_id',
  'rule',
  'ratio_note',
  'explanation',
  'confidence',
  'review_note',
]);

const substitutions = substitutionRows.map((r) => ({
  from_id: r.from_id,
  to_id: r.to_id,
  rule: r.rule,
  ratio_note: r.ratio_note === '' ? null : r.ratio_note,
  explanation: r.explanation,
  confidence: r.confidence,
  review_note: r.review_note,
}));

writeFileSync(join(HERE, 'ingredients.json'), `${JSON.stringify(ingredients, null, 2)}\n`);
writeFileSync(join(HERE, 'substitutions.json'), `${JSON.stringify(substitutions, null, 2)}\n`);

/* ---------------------------------- SQL ----------------------------------- */

/**
 * bootstrap.ts loads `.sql` files listed in seed/MANIFEST, so the JSON is
 * rendered to idempotent SQL here rather than teaching bootstrap a second
 * format. `INSERT OR REPLACE` makes a second run overwrite rather than
 * duplicate, which is what "safe to run twice" requires (section 13).
 *
 * `confidence` and `review_note` are dropped: they are review metadata and the
 * D1 `ingredients` table has no such columns.
 */
const q = (v) => (v === null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

const ingredientSql = [
  '-- Generated by seed/build-seed.mjs. Do not edit; edit ingredients.tsv.',
  'BEGIN TRANSACTION;',
  ...ingredients.map(
    (r) =>
      `INSERT OR REPLACE INTO ingredients (canonical_id, name, aliases, category, default_unit, default_shelf_days, allergens, diet_flags) VALUES (${q(r.canonical_id)}, ${q(r.name)}, ${q(JSON.stringify(r.aliases))}, ${q(r.category)}, ${q(r.default_unit)}, ${r.default_shelf_days === null ? 'NULL' : r.default_shelf_days}, ${q(JSON.stringify(r.allergens))}, ${q(JSON.stringify(r.diet_flags))});`,
  ),
  'COMMIT;',
].join(chr10);

const substitutionSql = [
  '-- Generated by seed/build-seed.mjs. Do not edit; edit substitutions.tsv.',
  'BEGIN TRANSACTION;',
  ...substitutions.map(
    (r) =>
      `INSERT OR REPLACE INTO substitutions (from_id, to_id, rule, ratio_note, explanation) VALUES (${q(r.from_id)}, ${q(r.to_id)}, ${q(r.rule)}, ${q(r.ratio_note)}, ${q(r.explanation)});`,
  ),
  'COMMIT;',
].join(chr10);

writeFileSync(join(HERE, '010_ingredients.sql'), `${ingredientSql}`+chr10);
writeFileSync(join(HERE, '020_substitutions.sql'), `${substitutionSql}`+chr10);

/* --------------------------------- REVIEW --------------------------------- */

const byConfidence = (rows, level) => rows.filter((r) => r.confidence === level);

const count = (rows) => ({
  high: byConfidence(rows, 'high').length,
  medium: byConfidence(rows, 'medium').length,
  low: byConfidence(rows, 'low').length,
});

const ing = count(ingredients);
const sub = count(substitutions);

const table = (rows, kind) =>
  rows
    .map((r) =>
      kind === 'ingredient'
        ? `| \`${r.canonical_id}\` | ${r.allergens.join(', ') || '—'} | ${r.diet_flags.join(', ') || '—'} | ${r.review_note} |`
        : `| \`${r.from_id}\` → \`${r.to_id}\` | ${r.rule} | ${r.review_note} |`,
    )
    .join('\n');

const review = `# Seed data review list

Generated by \`node seed/build-seed.mjs\`. Do not edit by hand — edit the
\`confidence\` and \`review_note\` columns in the TSVs and rebuild.

Every entry below is one I could not verify. This list is generated from the
confidence column, not curated, so it is complete with respect to what the data
claims about itself. It does **not** mean everything marked \`high\` is correct —
it means I had no specific doubt about it.

## Counts

| | high | medium | low | total |
| --- | ---: | ---: | ---: | ---: |
| Ingredients | ${ing.high} | ${ing.medium} | ${ing.low} | ${ingredients.length} |
| Substitutions | ${sub.high} | ${sub.medium} | ${sub.low} | ${substitutions.length} |

## What the levels mean

- **low** — a composite or commercial product whose recipe varies by brand.
  An allergen here is a guess about a typical formulation, not a fact about a
  specific product. **Check these first.**
- **medium** — allergens are probably right; the shelf life is a guess, or the
  name is regional and may map to something else in your kitchen.
- **high** — common ingredient, unambiguous allergens, well-known shelf life.

## Priority 1 — low confidence ingredients (${ing.low})

These carry allergen claims I cannot stand behind. Most are commercial blends
where the answer is genuinely brand-dependent, which means the taxonomy may
need per-brand entries rather than one row.

| id | allergens | flags | why |
| --- | --- | --- | --- |
${table(byConfidence(ingredients, 'low'), 'ingredient')}

## Priority 2 — low confidence substitutions (${sub.low})

| swap | rule | why |
| --- | --- | --- |
${table(byConfidence(substitutions, 'low'), 'substitution')}

## Priority 3 — medium confidence ingredients (${ing.medium})

| id | allergens | flags | why |
| --- | --- | --- | --- |
${table(byConfidence(ingredients, 'medium'), 'ingredient')}

## Priority 4 — medium confidence substitutions (${sub.medium})

| swap | rule | why |
| --- | --- | --- |
${table(byConfidence(substitutions, 'medium'), 'substitution')}

## Known systemic gaps

These are not individual entries but properties of the whole dataset:

1. **Shelf life is the weakest field throughout.** It varies with storage,
   season and packaging, and none of it is measured. An expiry estimate that is
   wrong by a few days is an annoyance; treat it as such, not as data.
2. **Rennet is under-recorded on cheese.** Parmesan, pecorino and several
   others are traditionally made with animal rennet, which makes them not
   vegetarian. Where I knew, the \`animal_derived\` flag is set. Where a
   vegetarian version is common the entry is marked medium. A vegetarian user
   trusting a cheese entry is a real failure mode.
3. **Asafoetida is wheat-compounded in most Indian brands.** \`asafoetida\`
   carries gluten and \`asafoetida_gf\` does not. Every Jain and sattvic
   substitution points at \`asafoetida_gf\` deliberately. If your hing is the
   ordinary kind, the gluten-free swaps are wrong.
4. **Cross-contamination is out of scope** (section 7). Nothing here models
   shared fryers, shared lines or "may contain" labelling. Oats, sev and
   chocolate are the obvious cases.
5. **Regional names collide.** Several Hindi and romanised aliases map to
   different plants in different regions. If an alias looks wrong for your
   kitchen, it probably is for someone else's too.
`;

writeFileSync(join(HERE, 'REVIEW.md'), review);

console.log(`ingredients.json   ${ingredients.length} entries`);
console.log(`substitutions.json ${substitutions.length} entries`);
console.log(`010_ingredients.sql, 020_substitutions.sql written`);
console.log(
  `REVIEW.md          ${ing.low + sub.low} low, ${ing.medium + sub.medium} medium to check`,
);
