/**
 * Shared helpers for the six week-1 spikes. Each spike Worker runs its
 * experiment and returns a finished RESULT.md body as `text/markdown`; the
 * runner in `spikes/run.mjs` only has to save it. That keeps every spike a
 * single file with no templating step.
 */

export interface AiUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
}

export interface AiToolCall {
  name?: string;
  arguments?: unknown;
  function?: { name?: string; arguments?: unknown };
}

export interface AiTextResult {
  response?: string;
  tool_calls?: AiToolCall[];
  usage?: AiUsage;
}

export interface AiGatewayOptions {
  id: string;
  cacheTtl?: number;
  skipCache?: boolean;
}

export interface AiRunOptions {
  gateway?: AiGatewayOptions;
  returnRawResponse?: boolean;
}

export interface AiBinding {
  run<T = AiTextResult>(
    model: string,
    input: Record<string, unknown>,
    options?: AiRunOptions,
  ): Promise<T>;
}

/** Milliseconds elapsed since the call, rounded. */
export function timer(): () => number {
  const start = Date.now();
  return () => Date.now() - start;
}

export function errText(e: unknown): string {
  if (e instanceof Error) return `${e.name}: ${e.message}`;
  return String(e);
}

/** Collapses an error or object to one markdown-table-safe line. */
export function cell(v: unknown): string {
  const s = typeof v === 'string' ? v : JSON.stringify(v);
  return (s ?? 'null').replace(/\|/g, '\\|').replace(/\n+/g, ' ').slice(0, 300);
}

export function table(headers: string[], rows: unknown[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const rule = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.map(cell).join(' | ')} |`).join('\n');
  return [head, rule, body].join('\n');
}

export function pct(part: number, whole: number): string {
  if (whole === 0) return 'n/a';
  return `${((part / whole) * 100).toFixed(1)}%`;
}

export function mean(xs: number[]): number {
  if (xs.length === 0) return 0;
  return xs.reduce((a, b) => a + b, 0) / xs.length;
}

/** Wraps a spike body in the common RESULT.md frame. */
export function result(opts: {
  n: number;
  title: string;
  question: string;
  decides: string;
  answer: string;
  body: string;
}): Response {
  const md = `# Spike ${opts.n} — ${opts.title}

**Question (spec section 14):** ${opts.question}

**Decides:** ${opts.decides}

**Run at:** ${new Date().toISOString()}

## Answer

${opts.answer}

${opts.body}

---

_Generated by \`node spikes/run.mjs ${opts.n}\`. Every number above was measured
in this run against a live Cloudflare account; nothing here is estimated unless
the row says so._
`;
  return new Response(md, {
    headers: { 'content-type': 'text/markdown; charset=utf-8' },
  });
}

/** Renders a thrown error as a valid RESULT.md, because a failure is also an answer. */
export function failed(opts: {
  n: number;
  title: string;
  question: string;
  decides: string;
  error: unknown;
  note?: string;
}): Response {
  return result({
    n: opts.n,
    title: opts.title,
    question: opts.question,
    decides: opts.decides,
    answer: `**The spike did not complete.** It failed with:\n\n\`\`\`\n${errText(opts.error)}\n\`\`\``,
    body: opts.note ?? '',
  });
}
